### ISSUE TITLE
How would I go about sending my own custom email ? 

### ISSUE THREAD

**Issue by single-stop-rj** [graphql-devise/graphql_devise#117]
I'm looking for a way to pull the reset password token into my own trigger. Im having a hard time being able to use find_resource in an Active Record Model. 

something like this. 

```ruby
def send_complete_signup_email
    # redirect_url = "#{Rails.application.credentials.front_end_host}/case-management/reset-password"
    # auth_schema_url = "#{Rails.application.credentials.backend_end_host}/auth"

    resource = find_resource(:email, get_case_insensitive_field(:email, user.email))

    resource.send_reset_password_instructions(
        email: user.email,
        provider: 'email',
        redirect_url: redirect_url,
        template_path: ['case_manager_mailer'],
        schema_url: auth_schema_url
    )
  end
```

**Comment by mcelicalderon** [comment]
Hey @single-stop-rj! Please provide more context as I don't understand if this is a problem with the gem or just a question. Remember that in you context you should have access to `context[:controller]` where you can get information like `auth_schema_url` instead of having it as fixed value somewhere else. Find resource should be available in any mutation or resolver that inherits from or resolver or mutations.

**Comment by mcelicalderon** [comment]
Closing this one it would seem it is not a problem with the gem.

**Comment by single-stop-rj** [comment]
I guess this is the disconnect. I need a way to be able to generate the URL from outside of a controller. Like in the User model itself. 

I'm trying to customize the Devise Emails, and be able to pass in the params properly, all while being able to have custom Email templates. 

I know that the URLs are open in the context hash, its passing them, or accessing them in AR Models or ActiveJob that I have a little trouble with. 

Then customizing the devise mailers as well.
