### ISSUE TITLE
How to get credentials from Mutations signUp.

### ISSUE THREAD

**Issue by dwthien** [graphql-devise/graphql_devise#121]
Hi,
I have a question,
after SignUp, the database created new tokens, can Mutations signUp get credentials?
so we can save credentials and skip login action after Customer SignUp.

![image](https://user-images.githubusercontent.com/25741737/88812282-be5f8800-d1e1-11ea-8473-68b827e199fc.png)
![image](https://user-images.githubusercontent.com/25741737/88812787-53fb1780-d1e2-11ea-8c16-9f4e374c04ea.png)

**Comment by mcelicalderon** [comment]
Hey @dwthien! That's a god question. So right now, if you haven't enabled the confirmable module (no confirmation email is sent with a link in order to activate the newly created account), the signUp mutation will actually return credentials in the headers. Now, we can definitively include a new field in the mutation `credentials` as in the login mutation so it's easier to extract those on the client. Now, I guess the same logic would apply for the confirmable module. If you have confirmable enabled, the credentials field in the signUp mutation would be null as in theory you don't want an unconfirmed user go get credentials yet. Does this make sense?

**Comment by dwthien** [comment]
Hi @mcelicalderon 
you are right, I haven't enabled the confirmable module, so the credentials responded into headers, I missed this one, sorry.
But better if we can definitively field if we did not enable the confirmable module as you said.

Thank you for replying and support from you :)))

**Comment by mcelicalderon** [comment]
No problem! We'll add the field ASAP as it's definitively easier to handle, at least in Apollo.
