### ISSUE TITLE
Error code is overwritten when having defined rescue_from(StandardError)

### ISSUE THREAD

**Issue by alexanderdavide** [graphql-devise/graphql_devise#141]
### Describe the bug

The expected error code for unauthenticated requests `AUTHENTICATION_ERROR` seems to be overwritten when having defined `rescue_from(StandardError)`. However, without `rescue_from(StandardError)` the error code is `AUTHENTICATION_ERROR` as expected.

### Environment

```ruby
gem 'devise', '>= 4.7.1', '< 5.0.0'
gem 'devise_token_auth', '>= 1.1.4', '< 2.0.0'
gem 'graphql', '>= 1.11.6', '< 2.0.0'
gem 'graphql_devise', '>= 0.13.5', '< 1.0.0'
```

### Steps to reproduce

1. Setup an authenticated endpoint with graphql_devise
2. define a rescue_from(StandardError) in your AppSchema like this
```ruby
rescue_from(StandardError) do |err, _obj, _args, _ctx, _field|
    raise GraphQL::ExecutionError.new(err, extensions: { code: 'INTERNAL_SERVER_ERROR' })
end
```
3. call the authenticated endpoint with invalid credentials

### Expected behavior

Return AUTHENTICATION_ERROR as error code.

### Actual behavior

Error code is INTERNAL_SERVER_ERROR as defined in `rescue_from(StandardError)`. However, without `rescue_from(StandardError)` the error code is `AUTHENTICATION_ERROR` as expected.

**Comment by mcelicalderon** [comment]
Hey @alexanderdavide! If I'm reading this correctly I think this is the expected behavior of the graphql gem. You are rescuing standard error at the schema level, so that will capture any execution error from the gem which is something you probably don't want as that's the mechanism the gem provides to return top graphql errors [like this](https://graphql-ruby.org/errors/execution_errors.html).

I see how you might want to return a message for internal server errors the graphql way and I'm not sure if the specification says something about this but I still handle those at the http layer by reading the 500 code.

Now, one thing you could do if you want to keep the standard error rescue at the schema level, is to check the type of the error in the block. So, 
```ruby
if err.is_a?(GraphQL::ExecutionError)
  raise err
else
  raise GraphQL::ExecutionError.new(err, extensions: { code: 'INTERNAL_SERVER_ERROR' })
end
```
Make sure yo use is_a? and not instance_of? As you do want to capture all those errors that inherit from that error like the one this gem raises.

Hope that helps. Let me know if I'm missing something.

**Comment by alexanderdavide** [comment]
@mcelicalderon Thank you! This helped indeed. I will look into field level errors.
Closing this issue.

**Comment by mcelicalderon** [comment]
Glad it helped! And actually thought of another reason not to capture standard error there. That would prevent an error catching tool like airbrake to grab those. So, careful with that.
