### ISSUE TITLE
Is the gem ready for production of react-native apps?

### ISSUE THREAD

**Issue by kockok** [graphql-devise/graphql_devise#52]
### Question

During the setup procedure of this gem, I happen to encounter loads of path redirects.
However, the userLogin response didn't even have a token provided.
So, It would be helpful if there's a little demo app for react-native.

**Comment by 00dav00** [comment]
Hi @kockok, currently the approach regarding auth info is the same as [devise-token-auth](https://github.com/lynndylanhurley/devise_token_auth), this means the tokens are sent in the response headers. You can check [this spec](https://github.com/graphql-devise/graphql_devise/blob/master/spec/requests/mutations/login_spec.rb#L28) for an example on how this works.

There is an [open issue](https://github.com/graphql-devise/graphql_devise/issues/50) about returning the auth info as part of gql response since this seems to be a common case. We are planning to add this as soon as our schedule allow us, but PRs are welcome ;)

About a demo app for react native, I think that is a great idea, I think we should add something like this. WDYT @mcelicalderon ?

Is this the info you were looking for @kockok?

**Comment by mcelicalderon** [comment]
I think @aarona might have worked on an example react app. But yes, as @00dav00 mentioned, the tokens are returned in the headers of the response. I have used this gem with an angular application and Apollo personally. I had to use `ApolloLink` to achieve this. Something like this
```typescript
const afterwareLink = new ApolloLink((operation, forward) => {
  return forward(operation).map(response => {
    if (operation.operationName == 'loginUser' && !response['errors']) {
      const context = operation.getContext();
      const { response: { headers } } = context;

      if (headers) {
        myService.storeCredentials(headers).then(() => {
          console.log('credentials stored');
        });
      }
    }

    return response;
  });
});
```
I'm not a front-end developer, so I'd love some input on this matter. As @00dav00 mentioned, we plan to add another field to the login mutation that would be of an object type containing all required fields (access-token, client, uid, expiry) while we still return the same info on the headers.

I hope this gives you a bit of a clue on how to achieve this @kockok and I'll try to work on adding that field to the login mutation ASAP.

**Comment by aarona** [comment]
@kockok I was looking into this myself and came across a bit of a road block. Not really React related but I think Apollo related. I was trying to figure out how to have to Apollo providers but I think what you have to do is use your Apollo provider for your main queries and when trying to access your authentication graphql endpoint, you'll need to create a link/provider on the fly which looks like what @mcelicalderon is doing here.

As a side note, I'm considering the security issues of storing the credentials in localStorage/unsecured cookies (non HTTP Only) and potentially looking at reworking DTA to send back a JWT with all the header information stored in the JWT's payload. I'm also thinking about how to use to tokens. one for access (expires in 15 minutes) and the other as a refresh token (expires after 7 days for example) so that it will automatically create a new access token using the refresh token and [`TokenRefreshLink`](https://github.com/newsiberian/apollo-link-token-refresh). If any of you guys have any solutions to this using the current implementation of DTA. (secure cookie that allows automatic refreshing) let me know otherwise I may need to look into rolling my own back end solution.

**Comment by mcelicalderon** [comment]
DTA allows via configuration (is actually default) to refresh tokens in every request you make. We do not plan to include different authentication schemas on this gem in the near future @aarona. For now just wrapping DTA's code in a graphql interface.

**Comment by mcelicalderon** [comment]
@kockok I'm merging #55 which adds credentials to the login mutation payload type. So now you can do
```graphql
mutation {
  userLogin(
    email: "#{user.email}",
    password: "#{password}"
  ) {
    authenticatable { email name }
    credentials { accessToken uid tokenType client expiry }
  }
}
```
