### ISSUE TITLE
graphql dual endpoint integration problem

### ISSUE THREAD

**Issue by kockok** [graphql-devise/graphql_devise#60]
### Question
![71514019-d384d900-28d7-11ea-8363-f480201caf41](https://user-images.githubusercontent.com/232541/73138109-fbfc2080-4099-11ea-8d00-e3054598221f.png)

I have `/auth` and the typical `/graphql` endpoints.
I use apollo with react-native.

The problem is that when I  use the `/auth` the endpoint to login and it's successful,
however, when I try to use the `/graphql` endpoint to fetch data, the app just got refreshed and logged out with the `/auth` endpoint.

```
const jclient = new ApolloClient({
  link: 'http://localhost:3000/graphql',
  cache: new InMemoryCache(),
});

const {loading, error, data} = useQuery(GET_DOGS, {
  client: jclient,
});
```

So, I wonder if it's right to use two endpoints for graphql.

Thanks.

**Comment by aarona** [comment]
I've yet find a good solution to this myself. ApolloClient doesn't really support multiple GraphQL endpoints but there seems to be something called [Apollo Federation](https://www.apollographql.com/docs/apollo-server/federation/introduction/) which I haven't looked into much because it seemed at face value it wasn't going to solve my problem.

There seems to be a consensus that you use [one](https://github.com/graphql/graphql-spec/issues/569) and my guess is that Facebook probably checks for a valid user inside their mutations/queries instead of preventing unauthenticated users from even hitting the data GQL endpoint.

**Comment by mcelicalderon** [comment]
As I mentioned before, I don't have enough react experience to answer this. But I did use this gem with Apollo and Angular without issues. I definitively supports multiple Graphs. From what I've read react should too, I even saw some commits on the framework that specifically enable multiple clients. Probably it is just not well documented yet.

About having a single endpoint. I guess that would be ideal, but Apollo should expect an app to consume from multiple graphql schemas (and it does, based on my angular experience) as you might consume third party services in the same app. And Graphql actually states that a separate app layer should do authentication before ever getting to the graphql schema [here](https://graphql.org/learn/serving-over-http/#web-request-pipeline)

**Comment by kockok** [comment]
Yes, Apollo does support multiple endpoints via the `client` option.
And yet, the problem I am facing is that once I switch to another ApolloClient instance, the whole auth mechanism breaks.
I hope someone also using react-native could give me a hint.

**Comment by mcelicalderon** [comment]
I'm closing this one as it's not really related to the gem, but to the specific Apollo client on react. Of course, feel free to post and discuss here any possible solutions. [This article](https://medium.com/open-graphql/apollo-multiple-clients-with-react-b34b571210a5) discusses some possible approaches. I will look into `Apollo Federation` as a possible way to solve this problem on the backend., but not sure it will be possible.
