### ISSUE TITLE
A way to support OTA in the GQL Devise Schema

### ISSUE THREAD

**Issue by single-stop-rj** [graphql-devise/graphql_devise#95]
### Question
I'm looking at setting up some OTA for a subset of users, but I'm not sure how I can expand the GraphQL Devise schema to support this. We are current;y running side by side /graphql and /auth endpoints. 

Basically looking for a way to pass an email address/phone number to the auth endpoint that would trigger the MFA to fire, and the other endpoint that would accept the 5 digit code.

**Comment by 00dav00** [comment]
Hey @single-stop-rj, to achive this you most likely have to set your own mutation for login. There is an example of how to do this in the rails dummy we are using to run the specs.

The steps would be:
- Create you own login mutation ([example in the specs](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/app/graphql/mutations/login.rb))
- Use this mutation when mounting the resources in the routes ([example in the spec](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/config/routes.rb#L3))

Don't forget that calling  super in your custom mutation is very important, otherwise the jwt token wont be created.

Is this the information you were looking for?

**Comment by single-stop-rj** [comment]
Sort of. I mean. I guess I want to support the original way. looking at the demo app, it seems as if I should be able to just create my own mutations and load them via the class inheritance. 

I think a requestOTA mutation where the params could be email address or phone number, and the a verifyOTA mutation that will accept the passcode, and then assign the authenticatable user to the proper context. 


just thinking out loud in case anyone else finds this

**Comment by 00dav00** [comment]
@single-stop-rj You can also add custom [mutations](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/config/routes.rb#L5) and [queries](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/config/routes.rb#L7) to the auth schema if that fits your project needs better.

Quick question, with OTA you are referring to something like [this](https://en.wikipedia.org/wiki/One-time_password)?

**Comment by single-stop-rj** [comment]
Yep. looking at incorporating Twilio and [this](https://github.com/heapsource/active_model_otp) so that users can have MFA / or OTAC(one-time access codes)  / OTP (one-time passwords )

**Comment by 00dav00** [comment]
I worked on a project with OTP recently and the solution was the following:
- Add additional param to login mutation for the otp
- When the otp param is not send the login mutation will verify user/password and send the otp
- When the otp param is send the login mutation will verify user/password and otp and create the jwt token

In that case we already knew the email/phone of the user, but I think it can be added as an additional param too. 
Of course if you find adding additional mutations/queries more suitable for your project that is always an option.

**Comment by single-stop-rj** [comment]
That's a good approach, handling it in one mutation. I think my reasoning behind the separation would be to understand the separate processes and not have this master mutation that would handle all of the cases. Sort of a Single Responsibility thing. But, I'll play around with it. Thanks for the links!
